server_listen: :8080
# server_tls_key: cmd/go-graphkb/keys/server.key
#Â server_tls_cert: cmd/go-graphkb/keys/server.crt

mariadb_username: graphkb
mariadb_password: password
mariadb_host: db
mariadb_database: graphkb
