language: go

go:
  - 1.13.x

script:
  - .travis/run.sh

before_deploy:
  - tar cvf graphkb-$TRAVIS_TAG.tar.gz web/build go-graphkb importer-csv
  - echo Deploying GraphKB $TRAVIS_TAG to GitHub Releases
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: "graphkb-$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  on:
    tags: true
