version: "3"
services:
  db:
    image: mariadb
    restart: always
    command: "--innodb-buffer-pool-size=4294967296 --innodb-buffer-pool-instances=8"
    # big setup
    # command: "--innodb-buffer-pool-size=17179869184 --innodb-buffer-pool-instances=16 --performance_schema=on --query_cache_type=off --query_cache_size=0 --innodb_log_file_size=1073741824 --innodb_io_capacity=2000"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: graphkb
      MYSQL_USER: graphkb
      MYSQL_PASSWORD: password
    ## Uncomment to persist database on host disk
    # volumes:
    #   - /var/lib/go-graphkb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  frontend:
    build:
      context: docker
      dockerfile: Dockerfile.frontend
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: "sh -c 'npm ci && npm run start'"
    working_dir: "/app"
    volumes:
      - ./web:/app
    ports:
      - 3000:3000

  graphkb:
    build:
      context: docker
      dockerfile: Dockerfile.graphkb
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    entrypoint: "./scripts/graphkb-entrypoint.sh"
    command: "cmd/go-graphkb/config.yml"
    working_dir: "/app"
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 2345:2345
